version: "3.2"
volumes:
  mail_data:

services:
  haraka:
    build: .
    environment:
      HARAKA_ME: mailserver
      HARAKA_IN_USER: inbounduser@somedomain.com
      HARAKA_IN_PWD: "supersneekypassword"
      HARAKA_OUT_USER: o365user@somedomain.com
      HARAKA_OUT_PWD: "realysecret"
      HARAKA_OUT_DOMAIN: somedomain.com
      HARAKA_CERT_SUBJ: "/C=SE/ST=SomeRegion/O=ACME Inc/OU=It Department/CN=mailserver"
      HARAKA_LOGLEVEL: debug
    volumes:
      # this will override any HARAKA_ environment variables
      # but needs a `data.yml` file
      - './data.yml:/app/data.yml'
      # example for production
      # - mail_data:/app/haraka
      # example for development
      - "./mail_data:/app/haraka/"
      - "./templates:/app/templates/"
    ports:
      - 588:587
